// <auto-generated />
namespace GlsLeague.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _123123123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123123123));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251246193_123123123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
